apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect-deploy
  labels: 
    app: debezium-connect
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels: 
        app: debezium-connect
    spec:
      containers:
        - name: debezium-connect
          image: debezium/connect:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: my-kafka.default.svc.cluster.local:9092
            - name: GROUP_ID
              value: "1"
            - name: OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: STATUS_STORAGE_TOPIC
              value: connect-status
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect-service
  labels:
    app: debezium-connect-service
spec:
  type: NodePort
  ports:
    - name: debezium-connect
      protocol: TCP
      port: 8083
      nodePort: 30500
  selector:
      app: debezium-connect