apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
  labels: 
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels: 
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer:dev
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
              - name: ConnectionStrings__DefaultConnection
                value: Server=proxy-postgres-postgresql;Port=5432;Database=postgres;User Id=postgres;Password=passw0rd;
              - name: KafkaSettings__BootstrapServers
                value: my-kafka.default.svc.cluster.local:9092
              - name: KafkaSettings__GroupId
                value: 14